name: 'formal'

on: [ push, pull_request ]

jobs:

  formal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
    - run: docker run --rm -tv $(pwd):/src -w /src/formal -e BUILD_NAME=ACCEPTANCE ghdl/synth:formal make all
